services:
  gitlab:
    image: gitlab/gitlab-ce:17.4.3-ce.0
    container_name: gitlab
    restart: always
    hostname: 'localhost'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://localhost:8929'
        gitlab_rails['gitlab_shell_ssh_port'] = 2424
        gitlab_rails['initial_root_password'] = 'gogeta12'
        gitlab_rails['omniauth_providers'] = [
          {
            "name" => "github",
            "app_id" => "Ov23liApIQCIws2lPNRx",
            "app_secret" => "ab01477adb60033b66a2ed76a36074343e1b6c50",
            "args" => { "access_type" => "offline", "approval_prompt" => "" }
          }
        ]
    ports:
      - '8929:8929'
      - '443:443'
      - '2424:22'
    volumes:
      - './config:/etc/gitlab'
      - './logs:/var/log/gitlab'
      - './data:/var/opt/gitlab'
    shm_size: '256m'

